name: "Check spelling"
on:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v1.3.4
        with:
          files: "./swagger.yaml"
          inline: warning
          root: "."
          config: "./cspell.json"
